name: gate_admin
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.0-nullsafety.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_slider_drawer: ^2.1.1
  firebase_auth: ^3.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
